### ISSUE TITLE
Implement or discard additional features the new package makes natural

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#105]
Namely, 
- [x] Document (and implement support for) a workflow for repeating (or continuing, per #67) a run, possibly with adjusted parameters, using the `aronnax-merged.conf` file (ideally without overwriting it).
- [x] Perhaps write additional named input generators, such as sinusoidal or stochastic wind, to recover the functionality lost through Issue #21 (or we can choose to just abandon that functionality, if it's not of general-enough usefulness).

**Comment by edoddridge** [comment]
I see repeating and continuing as quite different processes with different intentions. Namely:
- Repeating is useful for ensuring that results are as expected, and makes Aronnax a much more useful tool for improving reproducibility of numerical experiments in oceanography.
- Restarting may well involve changes to parameters and forcings. Say, for example, a simulation is spinning up from rest and gets to a point at which the velocities are large enough to violate a stability requirement. In that situation one would like to restart from the last viable output, but with a smaller timestep. There are also perturbation experiments in which the wind forcing is altered.

Those input generators should b very lightweight, and easy to incorporate and document. I'd like to see them included. At the very least they provide guidance on how one could go about producing the required time series for more general wind variations.

**Comment by axch** [comment]
Interestingly, I was imagining exactly the reverse use cases for parameter variations during repeats and restarts; namely, using repeats with different parameters to do sensitivity analysis on the results, and using restarts to recover from OS crashes during long jobs, or extending a successful but inconclusive simulation.

Clearly, it is appropriate to support adjusting the parameters in both circumstances.

**Comment by edoddridge** [comment]
#160 introduced functionality to restart the model from a checkpoint. However, it does not respect `aronnax-merged.conf` and will clobber it, using input values from `aronnax.conf` and the call to `driver.simulate`.

My feeling is that this preserves a more standard workflow - inputs are specified consistently, regardless of whether one is starting a new simulation or restarting an old one.

**Comment by edoddridge** [comment]
#119  implemented a generator function for time series inputs. My feeling is that allows users to easily specify their own time series and obviates the need for hard-coded sinusoidal or stochastic functions.
