### ISSUE TITLE
Incorrect initial average fields

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#107]
The Aronnax core dumps average fields at a configurable frequency.  If it is asked to make any such dumps at all, it makes one at the completion of the first time-step.  However, as of the first time step, there aren't very many past time steps to average over, so dividing by the dump rate causes the first reported average field to be scaled down and much too small.

**Comment by edoddridge** [comment]
Given that the supposedly averaged fields and the instantaneous fields are going to be identical after one time step, I think it makes sense simply to block the averaged output from being produced. 

I like having the instantaneous fields dumped after one time step - it can be very helpful for debugging.
