### ISSUE TITLE
Inconsistent interaction with 2d and 3d constructors

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#116]
The interface for the generators is currently inconsistent between the 2d and 3d versions. In particular, the 3d versions require a list of values of functions, while the 2d versions require a single value or function and throw an error if a list is passed.

This feels very odd when setting up a 1 or 1.5 layer simulation since the fields that could be 3d must be passed a list with a single value or function while the fields that are always a single layer are passed a value or function directly.

I propose we deal with this by getting rid of the 2d versions and adding a parameter to the 3d versions that tells it how many layers are in the field it returns. So the `interpret_requested_data` function still goes through the permissable shapes, but when it gets to something that must be 2d (e.g. wind stress) then the call is something like:
`return tracer_point_variable(grid, 1,  *requested_data)`
whereas the 3d version would be 
`return tracer_point_variable_2d(grid, grid.layers, *requested_data)`

This would require modifying the generators to be something like:
```
def tracer_point_variable(grid, field_layers, *h_funcs):
    X,Y = np.meshgrid(grid.x, grid.y)
    T_variable = np.ones((field_layers, grid.ny, grid.nx))
    assert field_layers == len(h_funcs)

    for i, f in enumerate(h_funcs):
        if isinstance(f, (int, long, float)):
            T_variable[i,:,:] = f
        else:
            T_variable[i,:,:] = f(X, Y)
    return T_variable
```

And thus, every generator would need to be passed a list of arguments, even if that list can only ever have one element.

**Comment by axch** [comment]
At that point, why not compute the number of layers from the length of the input list?  i.e., instead of
```
assert field_layers == len(h_funcs)
```
write
```
field_layers = len(h_funcs)
```

Does numpy produce the same results for `ones(1, 100, 100)` as it does for `ones(100, 100)`?  Methinks this method relies in that dimensionality pun, which is what causes me to feel weird about it.  If that pun works well, then doing this would, I think, simplify the interface nicely.

**Comment by edoddridge** [comment]
The assertion is intended to ensure that the user has provided a list of functions/values that is appropriate for the variable. Without it a 2D field could be passed a longer list and only the final entry would be used, or a 3D field could be passed a list that is too short and the final layers would be returned with the value 1 everywhere.

I was under the impression that numpy could handle additional axes gracefully. See e.g.
 - https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html
 - https://docs.scipy.org/doc/numpy/reference/generated/numpy.expand_dims.html

There is the possibility that the additional axis could confuse a user who might, justifiably, expect a 2D array to only have two axes, but currently these arrays are internal to the driver and get written out to files for the Fortran core to ingest.
