### ISSUE TITLE
Provide an option to dump fields at final timestep?

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#118]
I think it would be useful to include a parameter that makes the model produce output after the final timestep, perhaps `DumpAtLast`, or something similar.

**Comment by axch** [comment]
I think it would make for a cleaner end-user experience if this was either the default behavior, or part of a more complete restartability feature #67.  I assume you're envisioning a debugging iteration that consists of looking at the last field of a relatively short simulation while varying duration and other parameters?

**Comment by edoddridge** [comment]
Those are the two main uses - debugging and restarting. It would also protect the user from running a long simulation and not producing any output because they made a mistake calculating the dump frequency.

Your suggestion of wrapping this into the restartability feature is a good one, and dumping everything after the final timestep is, I think, a good default.
