### ISSUE TITLE
Character variable in Fortran core is too short

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#121]
While implementing a reproduction run I found that the character variable is too short to store 'input/wind_mag_time_series_file.bin', which is 35 characters long, while the variable currently has a max length of 30. This causes the Fortran core to look for the input at 'input/wind_mag_time_series_fil', and it raises an error about not being able to find the data it expects.

Increasing the max length to 60 solves the problem.

**Comment by axch** [comment]
There's also no reason not to bump the length limit for user-supplied inputs higher, to, say, 1000 or 10,000.  The cost in memory and allocation time for such a small number of character constants will be negligible, and doing so avoids leaving an annoying surprise for a user that wants long file names for some reason.  Irrelevant for names that are constructed by the Python wrapper, though, which may soon (already?) be all of them.  Also, is there any reason the length wasn't `*` to begin with?

@edoddridge Feel free to re-close with no action if you feel it would be appropriate.

**Comment by edoddridge** [comment]
It wasn't `*` because I didn't know how to do variable length strings. Making the length be `*` would be a more elegant long term fix than the simple work around I introduced.

However, if we do want to do that, I think it deserves its own ticket. This issue was resolved by bumping up to 60 characters
