### ISSUE TITLE
Set benchmark script to not run Hypre version by default

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#128]
As of #89 The benchmarking script currently tries to benchmark the core in n-layer mode using versions with and without Hypre. Since #89 was merged, this script fails on Travis because the Hypre subroutines are not found.

Potential solutions:
 - [ ] Don't try to benchmark Hypre by default
 - [ ] Have a command line argument to select whether Hypre should be benchmarked
 - [ ] Hack some code together to detect if Hypre is installed and select which benchmarks to run based on the outcome.

**Comment by axch** [comment]
I think the first two options you list are actually the classiest, on the grounds that our confidence in Hypre working at all makes publicly benchmarking it a little premature.
