### ISSUE TITLE
Ensure that progress reporting is on by default and user-friendly

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#13]
https://github.com/edoddridge/MIM/blob/master/MIM.f90#L748 appears to be somewhat terse progress reporting.  We should expand it to
- [ ] Be self-explanatory to someone who doesn't know the code
- [ ] Be silencable by a command-line switch (conventionally named `-q` or `--quiet`)

**Comment by axch** [comment]
The intrinsic `getarg(k, str_var)` fetches the kth command-line argument into the given string variable.  0 is the program name.

**Comment by edoddridge** [comment]
https://github.com/edoddridge/MIM/blob/master/MIM.f90#L748 doesn't actually print anything externally. It writes the loop counter "n" as a 10 digit integer to the variable "num". The num variable is then appended to names of the output files.

Currently the progress reporting consists of:
* these output dumps which occur every "dumpFreq" seconds of model time;
* averaged output dumps that occur every "avFreq" model seconds;
* a warning message if the sum of the layer thicknesses differs from the depth of the basin (https://github.com/edoddridge/MIM/blob/master/MIM.f90#L627)
* a warning message if a layer is thinner than hmin, which the user specifies in parameters.in at runtime (https://github.com/edoddridge/MIM/blob/master/MIM.f90#L657);
* a print out onto the terminal, a text file and termination of the run if a NaN is found - the chekc is performed when dumping the fields out to files (https://github.com/edoddridge/MIM/blob/master/MIM.f90#L733 and https://github.com/edoddridge/MIM/blob/master/MIM.f90#L768);
* an error message during the matrix inversion if the maximum number of steps has been exceeded before the convergence criterion is reached - this throws a warning message, but the simulation continues (https://github.com/edoddridge/MIM/blob/master/MIM.f90#L1289)
* a confirmation text file and message in the terminal specifying a successful completion when the model performs the specified number of time steps.

**Comment by axch** [comment]
Split the "silencable" part into Issue #85.
