### ISSUE TITLE
Implement periodic boundary conditions

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#15]
The source comment at https://github.com/edoddridge/MIM/blob/9adaded177146e50a9cea68b64bd5080cf13939b/MIM.f90#L246 deserves to be its own issue.

@edoddridge I understand the `regrid` branch exists for this purpose.  Care to elaborate on your plan of attack, impediments, acceptance criteria, etc?  If the work is done, then just enough to document your intentions for posterity :)

**Comment by edoddridge** [comment]
This is one of the main purposes of the `regrid` branch along with making the shape and size of the output data consistent with other C-grid ocean models (at the moment the master branch output includes some extra boundary points that are very useful for the model, but not particularly intuitive to the user).

The code on the `regrid` branch has been edited to alter the size of all arrays, the loop limits have been changed, and the matrix inversion subroutine has been modified. Currently the code on this branch compiles and runs (as can be seen in the output of the tests https://github.com/edoddridge/MIM/blob/regrid/examples/examples%20-%20n%20layer.ipynb), but it hasn't been properly tested yet.

I would like to compare the output of the simulations using the `regrid` version with the equivalent parts of the output from the `master` branch. If that comparison goes well, then I think this branch is ready to be merged.

**Comment by edoddridge** [comment]
I've compared output from the `regrid` branch and the `master` branch, and I'm happy that it's working as expected.

This branch does not implement periodic boundary conditions, but the changes in the grid should make that easier to implement at some stage in the future.

**Comment by rcmusgrave** [comment]
Here's an upvote for periodic boundary conditions. I would like to run channel configurations using this, and that would need periodic in one dimension... Thanks!

**Comment by edoddridge** [comment]
Thanks for the feedback Ruth! Consider it bumped up the priority list.

**Comment by rcmusgrave** [comment]
that was fast! I will try to set up my channel problem over the next few
weeks, will let you know how it goes. thanks!
