### ISSUE TITLE
Implement free surfaces

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#16]
The comment at https://github.com/edoddridge/MIM/blob/9adaded177146e50a9cea68b64bd5080cf13939b/MIM.f90#L306 deserves to be its own issue.

@edoddridge Care to comment?  What does this mean?  What work is needed to bring it about?

**Comment by edoddridge** [comment]
It should have been.

However, I'm pretty sure that https://github.com/edoddridge/MIM/commit/cf597928aa3e9137eb00bd8e4f935807271c7581 solved this problem - but the current test suite doesn't contain a simulation to test this assertion.

Essentially the model was putting too much energy into the barotropic mode (vertically homogeneous flow) and allowing the ocean surface to vary (having a free surface) meant that the model accumulated this error faster than when using a rigid lid (forcing the ocean surface to be flat at a prescribed height). I've disabled this warning in the regrid branch, and initial tests were positive, but I haven't properly tested the model with a free surface.
