### ISSUE TITLE
Periodic boundary conditions

### ISSUE THREAD

**Issue by navidcy** [edoddridge/aronnax#202]
Can I run the n-layer mode with periodic boundary conditions in one of the horizontal dimensions?

**Comment by navidcy** [comment]
Reading this:
http://aronnax.readthedocs.io/en/latest/running_aronnax.html#wetmaskfile
I figure out that you can do periodic only in one direction. But perhaps you should mention something along these lines where you write the equations that the model solves...

**Comment by edoddridge** [comment]
By default it's actually periodic in both horizontal directions regardless of which physics or solver is being used. To make it periodic in only one direction you need to specify a `wetmask` with a wall along one edge.

That paragraph is meant to explain how to make the domain not periodic by putting a wall along two of the edges (either the northern or southern to block meridional flow, and either the east or west to block zonal flow).

**Comment by edoddridge** [comment]
@navidcy - unless you have additional comments, I'll close this issue in favour of #203.
