### ISSUE TITLE
Minor equations typos/inconsistencies

### ISSUE THREAD

**Issue by navidcy** [edoddridge/aronnax#213]
1.  I believe there is a sign error in 
https://github.com/edoddridge/aronnax/blob/ed9500fc59cd49d4a1f762963a94eea8f96a604d/docs/aronnax_model.rst#L63
Ιt should read `+(f+ζ_n) x v_n`.

2. `ζ_n` should be defined.

3. After equation (1.2), why `g'=(ρ2-ρ1)/ρ1`. Eq. (1.2) refers to any layer `n`.

4. In equations (1.2) and (1.3) term `F_n` appears once divided by `ρ_0` and once not.

**Comment by edoddridge** [comment]
Thanks @navidcy! I'm just about to open a PR with fixes.

1. Absolutely. That is a mistake.

2. Yep. I just noticed that there are a few other variables there that should also be defined.

3. An oversight. Should be `g' = g*(rho_{n+1} - rho_{n})/rho_{0}`

4. Another mistake. They should both be divided by `rho_{0}`.
