### ISSUE TITLE
Can I involve the bathymetry in the two-layer model

### ISSUE THREAD

**Issue by shifei90** [edoddridge/aronnax#231]
Hi,

I have seen many interesting examples. I'm wandering whether the two-layer model can involve the bathymetry?

**Comment by edoddridge** [comment]
It certainly can. The example here: https://aronnax.readthedocs.io/en/latest/examples.html#yang-et-al-2016 uses a very simple bathymetry with a flat bottom surrounded by a slope near the edge.

To specify a non-trivial bathymetry, you need to provide an appropriate field using the `depthFile` parameter.

**Comment by shifei90** [comment]
Got it. Thank you, Edward.
