### ISSUE TITLE
An eddy stay the initial locaiton on the beta plane in Two-layer model

### ISSUE THREAD

**Issue by shifei90** [edoddridge/aronnax#232]
Dear, Edward

I run an example with an initial bump in the reduced gravity model and two-layer model on the beta plane, respectively. An eddy propagrate normally westward in the reduced gravity model. However, an eddy keep still and gradually decay in the two layer model. Why does it not propagrate westward. Is there anything wrong this example?

Some codes are as follows:

def bump(X, Y):
    iniH = 0. + 100*np.exp(-((6e5-X)**2 + (5e5-Y)**2)/(2*1e5**2))

def coriolis(X,Y):
    r = Y
    omega = 7.292115e-5    # (1/s)   (Groten, 2004)
    f0 = 2*omega*np.sin(15*np.pi/180)  # 3.77e-05
    beta = 2*omega*np.cos(np.pi*15/180)/6371e3   #2e-11
    f = f0 + beta*r

def beta_plane_bump_n_layer():
    print("Running n-layer beta-plane bump example")
    xlen = 2.0e6
    ylen = 1.5e6
    nx = 400
    ny = 300
    layers = 2 # also set in aronnax.conf file
    # aronnax.Grid(nx, ny, layers, dx, dy, x0=0, y0=0)
    grid = aro.Grid(nx, ny, layers, xlen / nx, ylen / ny, x0=120,y0=15)

    with working_directory(p.join(self_path)):
        drv.simulate(work_dir='.', config_path='aronnax.conf',
                     initHfile=[lambda X, Y: 100. + bump(X, Y),  800.],  
                     fUfile=[coriolis],
                     fVfile=[coriolis],                      
                     nx=nx, ny=ny, dx=xlen/nx, dy=ylen/ny,
                     exe='aronnax_external_solver',
                     dt=600, nTimeSteps=4640)

Thank you.

Fei

**Comment by edoddridge** [comment]
Hi Fei,

This looks ok to me.
It may be that the bottom drag is very strong, so the 2-layer simulation is dominated by the viscous stress, and the eddy decays rapidly.
Are you running each simulation for an equivalent amount of model time? You will likely need a shorter time step for the 2-layer simulation, so it will need more time steps.

**Comment by shifei90** [comment]
Thank you, Edward

You are right.

**Comment by edoddridge** [comment]
You're welcome. I'll close this issue since it seems like you've solved it.
