### ISSUE TITLE
Eliminate generated files from git

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#24]
The bug suspected by https://github.com/edoddridge/MIM/pull/20#issuecomment-282601196 is an instance of the general rule of thumb to keep auto-generated files out of version control.  To recap, the reasons for that advice are:
- It's easy for such files to grow stale, if one forgets to rebuild them in tandem with some other change (this is apparently what happened)
- Diffs to such files tend to be large, which is bad because
  - They are therefore prone to conflicts
  - Many such diffs will eventually degrade the performance of the version control system
- Junk will appear in `git grep` results (if the query string is short) (but perhaps this can be mitigated by configuration)

In my experience in academic settings, I have found one candidate exception: plotting results of computational experiments.  Checking the plot in allows someone to see it without having to (a) install and run the software that produces the plot, which, especially with academic software, tends to be a significant barrier, or (b) have enough computation and time to rerun the experiment, which can also be an issue.  In MIM's case, that exception is currently covered by the output cells of the example notebooks.

Ergo, I propose removing from version control
- [x] The input files from the examples (which requires automating their construction, but we have Python code for that)
- [x] The munged source and recompiled binaries that `run_examples.sh` already regenerates
- [x] The simulation outputs (see Issue #23)

If #23 happens first, it may be sensible to rewrite `run_examples.sh` in terms of using [nbconvert](http://nbconvert.readthedocs.io/en/latest/execute_api.html) to execute the example Jupyter notebooks.

**Comment by axch** [comment]
Accidentally came across another reason not to check in the input and output files: Fortran's "unformatted" file format is apparently system-dependent (for the sake of i/o performance), so may read differently if moved to a different machine.  Perhaps that's what happened in https://github.com/edoddridge/MIM/pull/20#issuecomment-282658521.

**Comment by edoddridge** [comment]
I think this makes sense. Having scripts to generate the input files when `run_examples.sh` is executed is a much better solution than having those inputs in the repo.

It would be great to automatically run a notebook after the examples have completed so that we still have a notebook with descriptions of the examples and some of the output plotted. 

Re system dependent binaries: that may be what's causing the issue in #20, but the reduced gravity examples all run on Travis-CI, which suggests something else is going on.

**Comment by edoddridge** [comment]
The remaining generated files in the repo were removed by #155. The only generated files left fall under the exception explicitly mentioned - plots of simulation outputs.
