### ISSUE TITLE
Code style - variable names and subroutines

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#40]
Because I've historically been inconsistent, the code currently contains examples of CamelHumped and snake_case variables and subroutines (sometimes even a [mixture of both in one](https://github.com/edoddridge/MIM/blob/master/MIM.f90#L902)). 

We should probably decide on one, implement it everywhere, and stick with it. snake_case?

**Comment by axch** [comment]
I prefer snake_case for Fortran.  Actually, I really prefer hyphen-case, but in masochistic programming languages like Fortran (and C, and Python, and Javascript) the hyphen clashes with infix subtraction, so I don't often get to have it.  Underscores are the next best thing.
