### ISSUE TITLE
Error and condition reporting strategy

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#45]
The MIM core currently follows a somewhat unusual pattern for reporting errors, warning conditions, and success.  To wit, for each kind of message, if that event occurs, it appends a descriptive message to a file on disk with a suggestive name.

The conventional thing for a program of this level of complexity is to write error and warning messages to the standard error stream, and routine notifications (such as progress and success reports) to the standard output stream.  By default those are interleaved in the controlling terminal, but may be redirected separately.
- Pro: This arrangement is very strongly conventional for command line tools, especially batch-mode ones with low interface complexity.  Conventionality is itself an advantage.
- Pro: Different types of messages will be interleaved in order of occurrence, preserving that information.  This may help the user diagnose any problems.
- Pro: The user interface is simpler: no need to describe what file names to look for.
- Con: Diagnostic output goes to an ephemeral location (the terminal) by default; but there are standard tools for controlling this (namely, shell redirection, `tee`, or `nohup`).  We can mention these in the user manual, if appropriate.
- Con: It is not apparent at a glance which conditions occurred during a run, as those lines may be buried in subsequent output.  This can be mitigated by printing a run summary at the end, or by the user applying `grep` to a saved log file.

**Comment by axch** [comment]
@edoddridge: I am compelled to ask, why did you code it the way it currently is?  Did I miss a consideration?

**Comment by edoddridge** [comment]
It's coded this way because I added the warnings and error messages in a piecemeal fashion as I was using the code and debugging simulations. The lack of coherent strategy and the flaunting of convention are not deliberate choices that were carefully considered.

Some models produce `stdout` and `stderr`  files by default to which the various outputs get redirected. The runtime switches then determine the level of output sent to these files - from virtually nothing to many diagnostics that substantially slow down the simulation.

**Comment by axch** [comment]
Yes.  Controlling logging by switch is the next level of sophistication, which can be added incrementally.

**Comment by axch** [comment]
Specific notifications the model currently emits:
- [ ] run completion at final time step.  Currently goes to file, should go to stdout.
- [ ] successful end of run.  Currently goes to stdout, as it should; but may be a duplicate.
- [ ] layer too thin warning.  Currently goes to file, should go to stderr.
- [ ] NaN detected error.  Currently goes to file and stdout, should go to stderr.
- [ ] depths must be positive error.  Currently goes to stdout, should go to stderr.
- [ ] maximum SOR iterations exceeded.  Currently goes to stdout, should go to stderr.
- [ ] unbalanced free surface warning.  Currently goes to stdout, should go to stderr.
