### ISSUE TITLE
Actually (re-)write introductory and conceptual documentation

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#61]
Presumably this will have a lot of overlap with the paper.

Components:
- [ ] Purpose and summary.
- [ ] Advertising (it's fast, it's easy to install and configure).
- [ ] Installation instructions.
- [ ] Usage examples (Issue #23).
- [x] What equations does the model solve?
- [ ] Numerical description: name of integration method, grid type, any other considerations.
- [ ] Maybe pointer to developer documentation, produced by Doxygen.
- [ ] Maybe pointer to auto-built test/example results, per #65.
- [ ] Comment that there is a separate Fortran program under all the Python, which can be invoked standalone profitably enough.

**Comment by edoddridge** [comment]
Definitely a lot of overlap, but also some quite different content. For example, I don't expect the paper to describe the installation procedure in detail.

**Comment by axch** [comment]
The ideal installation instructions are "pip install aronnax", which, to be true, calls for #87 being done.
