### ISSUE TITLE
Do we want to allow command-line overriding of parameters from `parameters.in`?

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#62]
Then the semantics of `parameters.in` becomes that it's the default configuration, and command-line arguments take precedence.

Considerations:
- Probably mostly relevant during fast-iteration exploration, or when automating multi-run batches.
- Pro: Becomes easier to vary model runs, exploring subsets of parameter space.
- Pro: Becomes easier to automate varying parameter space.
- Con: This would be pretty annoying to implement in the Fortran core, but not too bad in a Python wrapper.

For the sake of reproducibility, would want the program to dump its full configuration to a human- and machine-readable file.

This becomes more useful in conjunction with automatically computing the gridded input files from resolution-dependent sources, so that the model resolution can be easily varied.

**Comment by edoddridge** [comment]
I can see this could be useful, but how much value do you think it adds beyond us providing an example python script that automatically edits and creates a bunch of `parameters.in` files in appropriate directories?

**Comment by axch** [comment]
If I do this at all, I was thinking of making it be a feature of the Python wrapper program rather than the Fortran core.  In that case, much of the content of example vs implementation will be the same.

**Comment by axch** [comment]
Also agreed that this is not very high priority.
