### ISSUE TITLE
Restartability

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#67]
When a model run ends (ideally including interruption by an appropriate polite unix signal, like SIGHUP), it should dump all of its internal state (including tendencies), so that it can be restarted from that point.

Should add a "restart" option that reads tendencies from disk instead of starting up with Runge-Kutta; can also continue a sequence of snapshot numbers from where it left off.

**Comment by edoddridge** [comment]
This could be fairly elegantly incorporated by giving an `nTimeStep0` option - the timestep number at which the model is intended to restart. We could have some internal code that checks if that number is different from zero, and then it goes looking for the required inputs.
