### ISSUE TITLE
Align data layout between numpy arrays and Fortran raw files

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#83]
I am somewhat concerned by the data layout difference between Fortran and numpy.  There are a number of places in the I/O helpers where correct behavior requires matching dimensions and data layout:
- Generating input files for the Aronnax core, like here: https://github.com/axch/MIM/blob/packaging-rearrangement/aronnax/core.py#L93-L99.
- Reading the output, like here: https://github.com/axch/MIM/blob/packaging-rearrangement/aronnax/core.py#L83.
- Lining up grid points with function evaluations, like here: https://github.com/axch/MIM/blob/packaging-rearrangement/aronnax/core.py#L102-L104

So far our tests haven't failed because of any of this, but I would be much happier if we had some that had power to detect bugs of this kind.  For example, something like simulating a non-square grid, and checking that it's not being weirdly remapped.

**Comment by edoddridge** [comment]
This is a really good point.

I think the `DumpWind` flag will be useful here, because we can compare the original array with the array that has been exported by the python, gone into the Fortran, been exported by the Fortran, and then loaded into python. It won't necessarily tell us where in the chain the issue has occurred, but will tell us if everything is working as expected.

**Comment by axch** [comment]
Yes, that's one good check that we should definitely have.

I think there is one kind of problem that test won't catch, through, which is if the array translation is successfully inverted, but Fortran thinks the shape of the grid is different than Python thinks it is.  For example, if I ask for a 7x5, but those 35 numbers get interpreted as a 5x7 (and then flipped back on the reverse translation).  From Python's point of view, a mistake like that would manifest as the simulation thinking there are "edges" in the middle of the intended grid.  The ways I can think of to catch those would be with a non-square grid and strong edge effects, and/or a non-isotropic grid (i.e., very different dx and dy, and a test that checks the results of those are as expected).

**Comment by edoddridge** [comment]
The new test implemented in #196 uses a rectangular domain with sloping bathymetry. This means that any transposition errors will show as very strange bathymetry with obvious impacts on the flow - a visual inspection of the output shows no such issues. As such I'm happy to close this issue.
