### ISSUE TITLE
send stderr to a nicely named file

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#90]
On my machine the `stderr` stream goes to a file called "fort.17" - a more intuitive destination would be good.

**Comment by axch** [comment]
Interesting.  Are you setting the GFORTRAN_SOMETHING environment variable that the run scripts are supposed to set?  And are you compiling the core with gfortran?

**Comment by edoddridge** [comment]
Ah, OK.

I was running the core directly, and hadn't set that environment variable. Once I set it, the streams behaved nicely and I could easily pipe either stream to a file or let them print to terminal.

**Comment by edoddridge** [comment]
I was compiling with either gfortran or mpifort.

**Comment by axch** [comment]
OK.  mpifort is a wrapper, so, assuming it's picking up gfortran as the underlying compiler, that environment variable should work there too.

**Comment by edoddridge** [comment]
It did.

OK, so this is only relevant if someone runs the fortran core from outside the python wrapping and doesn't set the environment variable. I'm not sure that's worth worrying about.
