### ISSUE TITLE
Implement product shape

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#95]
Here is the external interface to Aronnax as I see it:
- either `$ aronnax simulate [OPTIONS] [directory]` or
- `from aronnax import simulate; simulate(directory=".")`
- reads aronnax.conf from path indicated by option (default directory/aronnax.conf)
- merges other options into defaults given by aronnax.conf.  Notable options:
  - Paths to input data in NetCDF format
  - Pointers to input data as in-memory numpy arrays
  - Names of input data as named generator functions with parameters
  - Directory to use to communicate with the core (default main working directory)
  - Directory to place output files in NetCDF format (default main/output)
- compiles the core with desired compilation options if necessary
  - Should not depend on make, but do its own content hashing.
    - Can also accept arbitrary compile options, presumably postfix (with some presets)
    - Can also accept arbitrary run prefixes, like valgrind and perf (with some presets)
- saves the configuration for reproducibility (ideally without overwriting the input)
- generates input files
  - interpolates given inputs if necessary
    - options for interpolation method, one of which is "error if interpolation is needed"
  - writes parameters.in and needful input files to the core working directory
- invokes the core in the core working directory
- reads the core files and converts them to NetCDF output format
- there should be an in-Python version that skips the NetCDF output and presents ability to read the raw core outputs into memory one by one
- Option sections in the conf file:
  - Each of the sections in parameters.in
  - Output handling (paths, anything else)
  - Compilation options for the core
  - Run prefixes for debugging the core?
- A description of each parameter should appear in
  - The online help of the executable
  - The generated documentation of the top level Python function
  - Comments in the example aronnax.conf file
  - Maybe comments in the example parameters.in file
  - Comments in the aronnax.conf file the program writes
  - Maybe comments in the parameters.in file the program writes

**Comment by axch** [comment]
Update: I have code almost ready for this and #96, pending some small cleanups.

**Comment by edoddridge** [comment]
I like the sound of this.

From reading this I get the impressions that the Fortran core will still output the raw Fortran files, but that the Python wrapper will then go scoop them up and output the data in NetCDF? 

Using NetCDF for the input is definitely a nice portable way to do it. My only thought is that it involves a little more effort for the users to create the files than simply dumping out binaries. My feeling is that it's worth it.

**Comment by axch** [comment]
Oh, if the users _want_ to dump binaries, I'm sure we can find a way for them to do that; but I'm presuming that NetCDF is a valuable format to support natively because users will have existing data (e.g., maps) in it.

**Comment by edoddridge** [comment]
That's true, but for the sorts of simulations Aronnx is likely to be used for, many users will simply create idealised basins and winds. Hence they may prefer to simply dump out binaries. However, if our wrapping makes is easy to create NetCDF files, then I don't think it's an issue.

**Comment by axch** [comment]
You'll be pleased to know that I haven't actually written any code for NetCDF input yet :)  Also, my draft has a (undocumented) interface for plugging in our or one's own Python functions for idealized conditions, so I assume that will work out pretty well.

**Comment by edoddridge** [comment]
Aha! An interface for specifying idealised functions is pretty much perfect, and totally negates my comment.
