### ISSUE TITLE
Discrepancy in dx values invalidates "known good" test outputs

### ISSUE THREAD

**Issue by axch** [edoddridge/aronnax#96]
The input generators in the test suite compute `dx` and `dy` as a function of the resolution, with a fixed total region size; whereas the core gets `dx` and `dy` values from the configuration file.  The latter is not kept in sync with the former, and they are, in the event, not equal, so the test suite runs with an inconsistent area configuration: input is generated assuming one spatial step size, but the simulation runs assuming another.

Work on #95 exposed this test suite problem; the blessed output will need to be regenerated.

**Comment by edoddridge** [comment]
Do you mean the lines in `output_preservation_test.py` where the grid is defined as 
`grid = aro.Grid(nx, ny, xlen / nx, ylen / ny)`?

Because I'm pretty confident that the grid generators will produce axis vectors with the expected `dx` if it is given to them as a parameter?
