### ISSUE TITLE
Incorrect layer thickness used in dudt and dvdt subroutines

### ISSUE THREAD

**Issue by edoddridge** [edoddridge/aronnax#98]
The layer thickness variable is on a different part of the grid to the velocities variables and the subroutines to calculate dvdt and dudt do not currently average the layer thickness on to these locations.

The offending code is:
`dudt(i,j,k) = dudt(i,j,k) + wind_x(i,j)/(rho0*h(i,j,k)) ! wind forcing`,
which should be 
`dudt(i,j,k) = dudt(i,j,k) + 2d0*wind_x(i,j)/(rho0*(h(i,j,k) + h(i-1,j,k))) ! wind forcing`

I found this while trying to solve the momentum discrepancy discovered while implementing #66.

That branch, `pysics-tests`, includes a fix for this, but it did not completely resolve the discrepancy.

**Comment by axch** [comment]
But reduced the discrepancy?  Interesting.

**Comment by edoddridge** [comment]
It doesn't actually reduce the discrepancy in these tests - I think the layer thickness deformations in these tests are too small to lead to it making a difference. It does however cause the two reduced gravity preservation tests with non-zero velocities to fail, so it does make a difference to those simulations, which is presumably a good thing.

**Comment by axch** [comment]
As with #74, there are two ways to approach an issue like this: Either leave the bug until the validation suite can decidedly detect it, or fix it now and file a ticket against the validation suite to develop a test case that can detect a reintroduction.

**Comment by axch** [comment]
Per discussion today, a plausible candidate test case is a configuration with a steep gradient in layer thickness (perhaps also a rapidly changing one), where we have some independent check on the expected behavior.  I am given to understand that some configurations have theoretically predictable <insert technical term here> behavior in the limit of long simulations, once a bunch of waves have dissipated.

**Comment by edoddridge** [comment]
This has been corrected in PR #120. The test suite could detect the change in the `dudt` subroutine, but not the `dvdt` subroutine (because there are currently no tests that include a meridional wind - see #6).

I've added the test suggested above to the list of physically motivated tests in #66 and will now close this ticket.
